### ISSUE TITLE
FAILED TO AUTHENTICATE

### ISSUE THREAD

**Issue by rserafim** [jlhernando/google-index-inspect-api#1]
Hello, I am getting FAILED TO AUTHENTICATE USER error. The json schema is different from what was downloaded on GCP.

The fields:
client_secret
redirect_uris
javascript_origins

I don't know how to stuff them.

It would be nice to keep the GCP default, as the repo uses https://github.com/swalker-888/google-indexing-api-bulk

Another question does this service send to Google to index, or does it just analyze the urls?

Thank you for your contribution

**Comment by sheirla** [comment]
Does this problem solved?

**Comment by jlhernando** [comment]
Hi @rserafim the client_secret file is the default file that you mention. You just have to create yours in your GCP account.

This service analyses if a URL is indexed or not indexed in Google.
